# Add 'Python Repo' label to any root file changes
Python Repo:
  - changed-files:
    - any-glob-to-any-file: 'setup.py'
    - any-glob-to-any-file: 'pythonrepo/*.py'

# Add 'Lint' label to any lint file changes
Linter:
  - changed-files:
    - any-glob-to-any-file: '.stickler.yml'
    - any-glob-to-any-file: '.hound.yml'
    - any-glob-to-any-file: '.yamllint.conf'
    - any-glob-to-any-file: '.flake8.ini'
    - any-glob-to-any-file: '.deepsource.toml'
    - any-glob-to-any-file: 'tests/check_*'

# Add 'Lang' label to any python file changes
Python Lang:
  - changed-files:
    - any-glob-to-any-file: '**/*.py'
    - any-glob-to-any-file: '*.py'

Configs:
  - changed-files:
    - any-glob-to-any-file: '*.yml'
    - any-glob-to-any-file: './**/*.yml'
    - any-glob-to-any-file: '*.ini'
    - any-glob-to-any-file: '*.toml'
    - any-glob-to-any-file: '*.cfg'
    - any-glob-to-any-file: 'requirements.txt'

# Add 'test' label
Testing:
  - changed-files:
    - any-glob-to-any-file: 'tests/**/*.py'
    - any-glob-to-any-file: 'tests/*'
    - any-glob-to-any-file: '.circleci/*'

CI:
  - changed-files:
    - any-glob-to-any-file: 'tests/*.py'
    - any-glob-to-any-file: '.stickler.yml'
    - any-glob-to-any-file: '.hound.yml'
    - any-glob-to-any-file: '.travis.yml'
    - any-glob-to-any-file: '.appveyor.yml'
    - any-glob-to-any-file: '.github/workflows/*'
    - any-glob-to-any-file: '.circleci/*'

Github:
  - changed-files:
    - any-glob-to-any-file: '.github/**/*'
    - any-glob-to-any-file: '.github/*'
    - any-glob-to-any-file: 'README.md'
