version: 1.0.{build}
branches:
  only:
  - master
  - stable
skip_tags: true
max_jobs: 1
image:
- Visual Studio 2017
- Visual Studio 2015
clone_depth: 50
init:
- cmd: >-
    choco install make

    choco install git

    choco install python3

    dir
build_script:
- cmd: make clean
test_script:
- cmd: >-
    make test

    make test-style
deploy: off