version: 1.0.{build}
branches:
  only:
  - master
  - stable
skip_tags: true
max_jobs: 1
image:
- Visual Studio 2017
- Visual Studio 2015
clone_depth: 50
init:
- cmd: >-
    choco install make || VER>NUL

    choco install git || VER>NUL

    choco install python --pre || VER>NUL

    choco upgrade python --pre || VER>NUL

    dir
build_script:
- cmd: make clean
test_script:
- cmd: >-
    make test || VER>NUL

    make test-style || VER>NUL
deploy: off