coverage:
  status:
    project:
      default: on
        target: 80%
        base: auto
      tests:
        target: 50%
        flags: tests
        paths:
          - tests

flags:
  tests:
    paths:
      - tests
    joined: false
