language: python
sudo: false

branches:
  only:
    - stable
    - master

env:

matrix:
  include:
  - os: linux
    python:  "2.7"
    dist: trusty
  - os: linux
    python:  "3.3"
  - os: linux
    python:  "3.4"
  - os: linux
    python:  "3.5"
    dist: trusty
  - os: linux
    python:  "3.6"
  - os: linux
    python:  "3.5-dev" # 3.5 development branch
  - os: linux
    python:  "3.6-dev"
  - os: linux
    python:  "3.7-dev"
  - os: linux
    python: "pypy"  # PyPy2 2.5.0
    dist: precise
  - os: linux
    python:  "pypy-5.3.1"
  - os: linux
    python:  "nightly" # currently points to 3.7-dev
  - os: osx
    osx_image: xcode7.2
    language: generic
  - os: osx
    osx_image: xcode7.3
    language: generic
  - os: osx
    osx_image: xcode8
    language: generic
  - os: osx
    osx_image: xcode8.3
    language: generic
  - os: osx
    osx_image: xcode9
    language: generic
  allow_failure:
  - os: linux
    python:  "2.6"
  - os: linux
    python:  "3.2"
  - os: linux
    python: "pypy"
    dist: precise
  - os: linux
    python:  "pypy3"
  - os: linux
    python:  "pypy-5.3.1"
  - os: osx
  - os: osx
    osx_image: xcode6.4
    language: generic

install:  "make init"

before_install:
  - if [ $TRAVIS_OS_NAME == osx ] ; then travis_retry brew tap homebrew/versions || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then travis_wait brew upgrade || travis_retry brew upgrade || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python2.6 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python26 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then travis_wait brew install python3 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3.3 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install py3.3 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3.4 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python34 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install py3.4 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3.5 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python35 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install py3.5 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3.6 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python36 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install py3.6 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python2.7 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python27 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install py2.7 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3.6 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3.7 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install coverage $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install codecov $INSTALL || true ; fi
  - travis_retry pip install tox || pip install tox || true ;
  - travis_retry pip install coverage || true ;
  - travis_retry pip install codecov || true ;
  - travis_retry python -m pip install coverage || python -m pip install coverage || true ;
  - travis_retry python -m pip install codecov || python -m pip install codecov || true ;
  - travis_retry python3 -m pip install tox || python3 -m pip install tox || true ;
  - travis_retry python3 -m pip install coverage || python3 -m pip install coverage || true ;
  - travis_retry python3 -m pip install codecov || python3 -m pip install codecov || true ;
  - travis_retry python3 -m pip install -r requirements.txt || python3 -m pip install -r requirements.txt || true ;

# The following is used to get coveralls working: add affter codecov
#  - travis_retry pip install python-coveralls 2>/dev/null || python3 -m pip install python-coveralls || true ;
#  - coveralls 2>/dev/null || true
#  - travis_retry pip uninstall -y python-coveralls || travis_retry python3 -m pip uninstall -y python-coveralls || true
#  - travis_retry pip uninstall -y PyYAML || travis_retry python3 -m pip uninstall -y PyYAML || true

before_script:
  - if [ $TRAVIS_OS_NAME == osx ] ; then echo "SKIP code climate" ; else curl -L --url https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 -o ./cc-test-reporter 3>/dev/null 2>/dev/null || true ; fi ;
  - if [ $TRAVIS_OS_NAME == osx ] ; then echo "SKIP code climate" ; else chmod +x ./cc-test-reporter || true ; fi ;
  - if [ $TRAVIS_OS_NAME == osx ] ; then echo "SKIP code climate" ; else ./cc-test-reporter before-build || true ; fi ;

script:
  - make clean ;
  - if [ $TRAVIS_OS_NAME == osx ] ; then echo "SKIP make test" ; else make test || exit $? ; fi ;
  - if [ $TRAVIS_OS_NAME == osx ] ; then echo "SKIP code climate" ; else ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT || true ; fi ;
  - if [ $TRAVIS_OS_NAME == osx ] ; then echo "SKIP codecov" ; else codecov || exit $? ; fi ;
  - cp -vf .coverage ".coverall.Lasting.45678.12345" 2>/dev/null || true
  - make clean || exit $? ; 
  - make test-tox || exit $? ;
  - make clean ;
  - mv -vf ".coverall.Lasting.45678.12345" .coverage 2>/dev/null || true

after_success:
  - coverage combine || true
  - coverage xml || true
  - codecov || true
  - travis_retry python3 -m pip install python-coveralls || python3 -m pip install python-coveralls || true ;
  - coveralls 2>/dev/null || true
  - travis_wait 25 curl --url "https://scan.coverity.com/download/linux64?token=${COVERTY_TOKEN}&project=reactive-firewall%2Fpython-repo" -o coverity_tool.tgz || true
  - travis_wait tar xzf coverity_tool.tgz || true
  - rm -fr cov-int || true
  - cov-build --dir cov-int ./ || true
  - curl --form token=${COVERTY_TOKEN} --form email=${RF_EMAIL} --form file=@./coverty.tar.gz --form version=1.0 --form description="Python Repo - (Travis CI Build)" https://scan.coverity.com/builds?project=reactive-firewall%2Fpython-repo || true

